#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/zoholike
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: false
#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false
#
#jwt:
#  # For HS512 algorithm, secret must be at least 64 bytes (512 bits)
#  secret: ${JWT_SECRET:change-me-to-a-strong-secret-key-at-least-64-bytes-512-bits-long-for-hs512-algorithm-please}
#  expiration-seconds: ${JWT_EXPIRATION_SECONDS:86400}
#
#  logging:
#    level:
#      org:
#        hibernate:
#          SQL: DEBUG
#          orm:
#            jdbc:
#              bind: TRACE
#          type:
#            descriptor:
#              sql:
#                BasicBinder: TRACE
#      com:
#        your company:
#          harms: DEBUG
#
